config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    root 'orders#index'
  end

  root 'pages#index'

  devise_for :users, :controllers => {registrations: 'registrations'}
  resources :users, only: [:show, :update] do
    collection do
      post :sms_verify
      get :sms_verify_form
      post :send_sms_code
      get :reset_password_form
      post :reset_password
    end
    member do
      post :check_phone
    end
  end
  resources :cars, only: [:create, :edit, :update, :destroy, :show]
  resources :bids, only: [:new, :create]

  get :my_profile, to: 'users#show'
  scope 'my_profile' do
    get :edit, to: 'users#edit'
    get :add_car, to: 'cars#new'
  end

  resources :orders, except: [:edit, :update] do
    collection do
      get :my
    end
    resources :comments
    resources :offers, only: :create
    member do
      post :close
      post :complete
    end
  end
  resources :offers do
    member do
      post :accept
      post :reject
    end
  end
  resources :documents

  namespace :admin do
    root 'users#index'

    resources :bids do
      collection do
        get :search_results
      end
      member do
        get :close
      end
    end

    resources :users do
      collection do
        get :inactive
        get :search_results
      end
      member do
        post :activate
        post :deactivate
        get :show_docs
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  include PgSearch
  pg_search_scope :search_everywhere,
                  against: %i[phone name surname],
                  using: {tsearch: {prefix: true},
                          trigram: {:threshold => 0.1}}
  before_validation :phone_number_format
  before_save :generate_sms_code, :generate_nikita_id

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:phone]
  validates :role, inclusion: {in: ['customer', 'admin', 'worker', 'manager']}

  validates :phone, presence: true,
            numericality: true,
            uniqueness: true,
            length: {is: 12}

  mount_uploader :avatar, AvatarUploader

  has_many :cars, dependent: :destroy
  has_many :documents, dependent: :destroy
  has_many :offers, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :worked_orders, foreign_key: 'worker_id', class_name: 'Order'
  has_many :comments, foreign_key: 'to_user_id'
  has_many :commented_on, foreign_key: 'from_user_id', class_name: 'Comment'

  ROLES = %w[ customer worker ]

  REGISTRABLE_ROLES = %w(customer worker)
  CREATABLE_ROLES = %w(admin manager customer worker)

  def phone_number_format
    self.phone = self.phone.tr('+()-', '')
    self.phone = '996' + self.phone if self.phone.size < 12
  end

  def admin?
    role == 'admin'
  end

  def manager?
    role == 'manager'
  end

  def inactive?
    !active?
  end

  def worker?
    role == 'worker'
  end

  def customer?
    role == 'customer'
  end

  def inactive_worker?
    inactive? && worker?
  end

  def activate
    update_attribute :active, true
  end

  def deactivate
    update_attribute :active, false
  end

  def profile_uncomplete?
    if role == 'customer'
      name.blank? || surname.blank? || phone.blank?
    elsif role == 'worker'
      name.blank? || surname.blank? || phone.blank? || cars.blank? || documents.blank?
    end
  end

  def blank_fields
    blank_fields = []

    blank_fields << 'name' if name.blank?
    blank_fields << 'surname' if surname.blank?
    blank_fields << 'phone' if phone.blank?
    blank_fields << 'car' if cars.blank? && role == 'worker'
    blank_fields << 'document' if documents.blank? && role == 'worker'

    blank_fields
  end

  def email_required?
    false
  end

  def email_changed?
    false
  end

  def cars_with_gps
    return [] unless worker_with_cars
    cars.reject {|car| car.imei.blank?}
  end

  def search_devices
    return [] unless worker?
    cars_with_gps.map(&:device)
  end

  def worker_with_cars
    worker? || !cars.blank?
  end

  def check_phone
    update_attribute :phone_checked, true
    activate if customer?
  end

  def uncheck_phone
    update_attribute :phone_checked, false
  end

  def generate_sms_code
    write_attribute(:sms_code, rand(1000..9999).to_s)
  end

  def generate_nikita_id
    write_attribute(:nikita_id, SecureRandom.hex(12).to_s)
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    where(phone: conditions[:phone].tr('+()-', '')).first
  end

  def rating
    average = Comment.where(:to_user_id => self.id).average(:rating)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  def index
    @users =  case params[:sort]
              when 'all'
                User.all
              when 'admins'
                User.where(role: 'admin')
              when 'workers'
                User.where(role: 'worker')
              when 'customers'
                User.where(role: 'customer')
              when 'inactive_workers'
                User.where(role: 'worker', active: false)
              when 'inactive_customers'
                User.where(role: 'customer', active: false)
              else
                User.all
              end
    @users = @users.page(params[:page]).per(10).order('created_at DESC')
  end

  def search_results
    @users = User.search_everywhere(params[:query])
    @users = @users.page(params[:page]).per(10).order('created_at DESC')
  end

  def inactive
    @users = User.where(active: false)
  end

  def new
    @user = User.new
  end

  def activate
    @user = User.find(params[:id])
    @user.activate
    redirect_to admin_users_path
  end

  def deactivate
    @user = User.find(params[:id])
    @user.deactivate
    redirect_to admin_users_path
  end

  def show_docs
    @user = User.find(params[:id])
    @documents = @user.documents
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to admin_users_path
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if params[:user][:password].blank? && params[:user][:password_confirmation].blank?
      params[:user].delete(:password)    
      params[:user].delete(:password_confirmation)
    end

    if @user.update(user_params)
      redirect_to admin_users_path
    else
      render 'admin/users/_form'
    end
  end

  def destroy
    User.destroy(params[:id])

    redirect_to admin_users_path
  end

  def user_params
    params.require(:user).permit(:name, :surname, :phone, :email, :password,
                                 :password_confirmation, :role)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  require 'net/http'
  before_action :authenticate_user!, only: [:edit, :update]

  def show
    @user = !params[:id].nil? ? User.find(params[:id]) : current_user
    @devices = @user.search_devices
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user

    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to my_profile_path, notice: 'Ваш профиль успешно обновлен' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def sms_verify
    if params[:sms_code_input] == current_user.sms_code
      current_user.check_phone
      redirect_to my_profile_path, notice: 'Номер телефона подтвержден'
    else
      redirect_back(fallback_location: root_path, notice: 'Неверный код')
    end
  end

  def send_sms_code
    if user_session['last_sms_time'].blank?
      user_session['last_sms_time'] = Time.now
      sms_sender(current_user.phone, current_user.sms_code, current_user.nikita_id)
    elsif !user_session['last_sms_time'].blank? && (Time.now - user_session['last_sms_time'].to_datetime).to_i > 3600
      user_session['last_sms_time'] = Time.now
      sms_sender(current_user.phone, current_user.sms_code, current_user.nikita_id)
      redirect_back(fallback_location: root_path)
    else
      redirect_back(fallback_location: root_path, notice: 'После отправки последнего смс прошло меньше часа')
    end
  end

  def sms_sender(phone, message, nikita_id)
    xml_string = xml_string_for_sms_send(phone,message, nikita_id)
    uri = URI.parse 'http://smspro.nikita.kg/api/message'
    request = Net::HTTP::Post.new uri.path
    request.body = xml_string
    request.content_type = 'text/xml'
    response = Net::HTTP.new(uri.host, uri.port).start { |http| http.request request }
    xml_doc = Nokogiri::XML(response.body)
    @status = xml_doc.css('status').first.text
    message = xml_doc.css('message').text
    @status == '0' ? flash[:notice] = 'СМС успешно отправлено' : flash[:danger] = message
  end

  def xml_string_for_sms_send(phone, message, nikita_id)
    '<?xml version="1.0" encoding="UTF-8"?>
    <message>
    <login>xak</login>
    <pwd>testpassword</pwd>
    <id>' + nikita_id + '</id>
    <sender>trucking.kg</sender>
    <text>' + message + '</text>
    <phones><phone>' + phone + '</phone></phones>
    </message>'
  end

  def check_phone
    user = User.find(params[:id])
    user.check_phone
    redirect_back(fallback_location: root_path)
  end

  def reset_password_form; end

  def reset_password
    user = User.find_by_phone(params[:phone_number])
    if user
      new_user_password = rand(100_000..999_999).to_s
      user.reset_password(new_user_password, new_user_password)
      sms_sender(user.phone,'Новый пароль: ' + new_user_password, user.nikita_id)
      redirect_to new_user_session_path
    else
      redirect_back(fallback_location: reset_password_users_path, notice: 'Пользователя с таким номер нет в системе')
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :surname, :avatar)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_customer.html.erb
<nav class="navbar navbar-default sidebar" role="navigation">
    <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-sidebar-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>      
    </div>
    <div class="collapse navbar-collapse" id="bs-sidebar-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active">
        	<%= link_to root_path do %>
					  <span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-road"></span>МОИ ЗАКАЗЫ
					<% end %>
        </li>
        <li class="active">
        	<%= link_to new_order_path do %>
					  <span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-th-list"></span>НОВЫЙ ЗАКАЗ
					<% end %>
        </li>
        <li class="active">
        	<%= link_to user_path(current_user) do %>
					  <span style="font-size:16px;" class="pull-right hidden-xs showopacity ic-user glyphicon glyphicon-user"></span>МОИ ПРОФИЛЬ
					<% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>
 

app/views/users/_form.html.erb
<% if @user.errors.any? %>
    <%= pluralize(@user.errors.count, "error") %> prohibited this article from being saved:
    <% @user.errors.full_messages.each do |msg| %>
        <%= msg %>
    <% end %>
<% end %>

<%= simple_form_for @user do |f| %>
    <%= f.input :name  %>
    <%= f.input :surname %>
    <%= f.input :avatar, as: :file %>
    <div class="form-actions">
      <%= f.button :submit %>
    </div>
<% end %>

app/views/users/_worker.html.erb
<nav class="navbar navbar-default sidebar" role="navigation">
    <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-sidebar-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>      
    </div>
    <div class="collapse navbar-collapse" id="bs-sidebar-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active">
          <%= link_to root_path do %>
            <span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-road"></span>ВСЕ ЗАКАЗЫ
          <% end %>
        </li>
        <li class="active">
          <%= link_to "#" do %>
            <span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-th-list"></span>МОИ ЗАКАЗЫ
          <% end %>
        </li>
        <li class="active">
          <%= link_to user_path(current_user) do %>
            <span style="font-size:16px;" class="pull-right hidden-xs showopacity ic-user glyphicon glyphicon-user"></span>МОЙ ПРОФИЛЬ
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/users/edit.html.erb
<div class="row">
  <div class="col-md-9 col-md-offset-2 toppad">
    <h2><%= t('update_profile')%></h2>
    <%= render 'form' %>
  </div>
</div>

app/views/users/reset_password_form.html.erb
<%= form_tag reset_password_users_path do %>
    <%= label_tag :phone_number, 'Номер телефона' %>
    <%= text_field_tag :phone_number %>
    <%= submit_tag 'Сбросить пароль', class: 'btn btn-default', id: 'password_reset' %>
<% end %>

app/views/users/show.html.erb
<div class="col-md-11 toppad">
  <div class="panel panel-info">
    <div class="panel-heading">
      <h3 class="panel-title"><%= @user.name %> <%= @user.surname %></h3>
    </div>
    <div class="panel-body">
      <div class="row">
        <div class="col-md-3 col-lg-3 " align="center">
          <%= image_tag @user.avatar.url(:avatarka), class:"img-responsive" %>
        </div>
        <div class=" col-md-9 col-lg-9 ">
          <table class="table table-user-information">
            <tbody>
            <tr>
              <td>Роль</td>
              <td><%= @user.role %></td>
            </tr>
            <tr>
              <td>Статус</td>
              <td><% if @user.inactive? %>
                    <small>Не активирован</small>
                  <% else %>
                    <small>Активирован</small>
                  <% end %>
              </td>
            </tr>
            <tr>
              <td><b>Рейтинг</b></td>
              <td><b>
                  <%= @user.rating %>
              </b></td>
            </tr>
            <tr>
              <td><b>Кол-во заказов</b></td>
              <td><b><%= @user.orders.count %></b></td>
            </tr>
            <tr>
              <td>Дата регистрации:</td>
              <td>06/23/2013</td>
            </tr>
            <tr>
              <td>Телефон</td>
              <td><%= @user.phone %></td>
            </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <% if @user == current_user %>
      <div class="panel-footer">
        <%= link_to 'Редактировать имя', edit_path, class: 'btn btn-success' %>
        <%= link_to 'Изменить телефон и пароль', edit_user_registration_path, class: 'btn btn-success' %>
        <%= link_to 'Добавить документы', documents_path, class: 'btn btn-info' if can? :read, Document %>
        <%= link_to 'Добавить машину', add_car_path, class: 'btn btn-info', id: 'add_car' if can? :create, Car %>
      </div>
    <% end %>
  </div>
  <%= render 'cars/panel' if @user.worker? %>
  <h3>Отзывы:</h3>
  <%= render @user.comments %>
</div>